import { StyleSheet, Font } from '@react-pdf/renderer';


Font.register({
    family: 'Alef',
    src: '/Alef/Alef-Regular.ttf',
});

export const styles = StyleSheet.create({
    page: {
        padding: 40,
        backgroundColor: '#FCFCFC',
        fontFamily: 'Alef',
    },
    header: {
        marginBottom: 20,
        borderBottom: '1px solid #050d2d',
        paddingBottom: 10,
    },
    headerTitle: {
        fontSize: 24,
        color: '#050d2d',
        textAlign: 'center',
        fontWeight: 'bold',
    },
    section: {
        marginBottom: 20,
        padding: 10,
        backgroundColor: '#F8F9FA',
        borderRadius: 5,
    },
    sectionTitle: {
        fontSize: 16,
        marginBottom: 10,
        color: '#050d2d',
        fontWeight: 'bold',
        borderBottom: '1px solid #DDD',
        paddingBottom: 5,
    },
    row: {
        flexDirection: 'row',
        marginBottom: 5,
    },
    label: {
        width: '30%',
        fontSize: 12,
        color: '#050d2d',
        fontWeight: 'bold',
    },
    value: {
        width: '70%',
        fontSize: 12,
        color: '#050d2d',
    },
    filterItem: {
        margin: 3,
        padding: '3 8',
        backgroundColor: '#050d2d',
        borderRadius: 10,
        fontSize: 10,
        color: '#FCFCFC',
        display: 'inline-block',
    },
    filtersContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 5,
    },
    conclusion: {
        fontSize: 12,
        lineHeight: 1.6,
        color: '#050d2d',
        textAlign: 'justify',
    },
    comparison: {
        marginTop: 20,
        padding: 10,
        backgroundColor: '#e3f2fd',
        borderRadius: 5,
        fontSize: 12,
        color: '#050d2d',
        textAlign: 'center',
    },
    metricHighlight: {
        backgroundColor: '#F0F2F5',
        color: 'white',
        padding: 10,
        borderRadius: 5,
        marginTop: 10,
        borderLeft: '4px solid #050d2d',
    },
    metricText: {
        fontSize: 12,
        color: '#050d2d',
        fontWeight: 'semibold',
    },
    graphSection: {
        marginVertical: 15,
        padding: 10,
        backgroundColor: '#FFF',
        borderRadius: 8,
        boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
    },
    graphTitle: {
        fontSize: 14,
        color: '#050d2d',
        marginBottom: 8,
        fontWeight: 'semibold',
    },
    comparisonSection: {
        marginTop: 15,
        paddingTop: 15,
        borderTop: '1px solid #DDD',
    },
    comparisonTitle: {
        fontSize: 14,
        color: '#050d2d',
        fontWeight: 'bold',
        marginBottom: 5,
        textAlign: 'center',
    },
    graphImage: {
        width: '100%',
        height: 210,
        borderRadius: 4,
        marginTop: 10,
        border: '1px solid #EEE',
    },
    comparisonImage: {
        width: '75%',
        height: 300,
        borderRadius: 4,
        border: '1px solid #EEE',
    },
    bigSourceImage: {
        width: '100%',
        height: 250,
        borderRadius: 4,
        border: '1px solid #EEE',
    },
    comparisonImagesContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
    },
    comparisonImageContainer: {
        flexBasis: '100%',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        textAlign: 'center',
        marginBottom: 10,
    },
    comparisonTable: {
        width: '100%',
        marginTop: 25,
        marginBottom: 20,
        borderRadius: 8,
        overflow: 'hidden',
        boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
        border: '1px solid #E0E0E0',
    },
    tableRow: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#E8E8E8',
        backgroundColor: '#FFFFFF',
        minHeight: 35,
        alignItems: 'center',
    },
    tableHeader: {
        width: '20%',
        padding: 10,
        backgroundColor: '#050d2d',
        fontSize: 11,
        fontWeight: 'bold',
        color: '#FFFFFF',
        textAlign: 'center',
        borderRight: '1px solid #FFFFFF',
    },
    tableCell: {
        width: '20%',
        padding: 10,
        fontSize: 10,
        textAlign: 'center',
        color: '#050d2d',
        borderRight: '1px solid #F0F0F0',
        backgroundColor: '#FAFAFA',
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 30,
        right: 30,
        textAlign: 'center',
        color: '#888',
        fontSize: 10,
        borderTop: '1px solid #DDD',
        paddingTop: 10,
    },
    dateText: {
        position: 'absolute',
        top: 30,
        right: 30,
        fontSize: 10,
        color: '#050d2d',
    },
    hebrewText: {
        direction: 'rtl',
        textAlign: 'right',
        fontFamily: 'Alef',
    },
    imageCaption: {
        fontSize: 10,
        color: '#050d2d',
        textAlign: 'center',
        marginTop: 5,
    },
});